### ISSUE TITLE
benchmark using apache bench got [GIN] WARNING. Headers were already written!

### ISSUE THREAD

**Issue by oknoorap** [gin-gonic/gin#264] opened 2015-04-19 07:12 UTC
Hello i'm using apache ab -n 1000 -c 10 -t 5 http://localhost:8888/my-page.html

here my codes

``` go
import(
    "./router"
    "github.com/gin-gonic/contrib/gzip"
    "github.com/gin-gonic/contrib/sessions"
    "github.com/gin-gonic/contrib/static"
    "github.com/gin-gonic/gin"
)

func main() {
web := gin.Default()
web.Use(gzip.Gzip(gzip.DefaultCompression))
web.Use(static.Serve("/", static.LocalFile("./public", true)))
web.Use(static.Serve("/admin/assets", static.LocalFile("./admin/assets", true)))
web.Use(sessions.Sessions("master", sessions.NewCookieStore([]byte("test"))))

// All Routers
web.GET("/", router.Index)
web.GET("/:page/*pages", router.Main)
web.NoRoute(router.NotRoute)
web.Run(":8888")
}
```

what's wrong with my code?

**Comment by dariusc93** [comment] 2015-05-08 01:44
@oknoorap have you found out the issue? For me, it came down to using the `static.Serve` and to be honest, I cannot get working for the left of me. I had to move over to macaron because i would get this message with a blank page, or i would get a index list on every page along with the content rendered out.

**Comment by jbrodriguez** [comment] 2015-05-14 18:38
I also receive this with static.Serve, can't figure it out though. #133 is similar, but was closed by @manucorporat last year.
Maybe this should be revisited.

**Comment by norx85** [comment] 2015-05-15 15:34
I have the same problem just using HTML function to render an html template:

    func getRequestTemplateHandler(c *gin.Context) {
	   c.HTML(200, "template.templ.html", gin.H{
		  "Done":     false,
		  "Imported": false,
	   })
    }

**Comment by manucorporat** [comment] 2015-05-15 15:38
I am going to review this today. anyway, [GIN] WARNING is just that, a warning.

**Comment by norx85** [comment] 2015-05-15 17:04
Yes it's just a warning, but a warning for every page served can create a serious memory leak after some days in a production environment with thousands of users a day

**Comment by oknoorap** [comment] 2015-05-15 19:08
Although this issue only warning, your browser will not renders output immediately, Imagine, if my site has traffic 20k perday, frontend will always waiting logs to be cleared first.

I agree console log display gin warning, but don't show output in console when this warning occured.

**Comment by manucorporat** [comment] 2015-05-24 01:08
@oknoorap @norx85
```go
web.Use(static.Serve("/", static.LocalFile("./public", true)))
```
is acting as a middleware in every single request... which is bad. probable the issue is:
static fails and set status code = 404, then the handle chain continues... and you change it to 200 here:

```go
web.GET("/", router.Index)
```

I would rewrite the code like this:
```go
import(
    "./router"
    "github.com/gin-gonic/contrib/gzip"
    "github.com/gin-gonic/contrib/sessions"
    "github.com/gin-gonic/contrib/static"
    "github.com/gin-gonic/gin"
)

func main() {
    web := gin.Default()
    web.Use(gzip.Gzip(gzip.DefaultCompression))
    web.Use(sessions.Sessions("master", sessions.NewCookieStore([]byte("test"))))

    // All Routers
    web.Static("/public", "./public")
    web.Static("/admin/assets", "./admin/assets")
    web.GET("/", router.Index)
    web.GET("/:page/*pages", router.Main)
    web.NoRoute(router.NotRoute)
    web.Run(":8888")
}
```

it uses the built-in Static() which is much performant and safe.

**Closed** 2017-07-02 12:12 UTC
