### ISSUE TITLE
gin.Context has no field or method FormValue

### ISSUE THREAD

**Issue by land-pack** [gin-gonic/gin#1399] opened 2018-06-20 10:22 UTC
My go version 

> go version go1.9.2 darwin/amd64

Go Env

> GOARCH="amd64"
> GOBIN=""
> GOEXE=""
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOOS="darwin"
> GOPATH="/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/go/bin"
> GORACE=""
> GOROOT="/usr/local/go"
> GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
> GCCGO="gccgo"
> CC="clang"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x4/v6pjwfwj3xn08hyt33nx8rz80000gq/T/go-build398879045=/tmp/go-build -gno-record-gcc-switches -fno-common"
> CXX="clang++"
> CGO_ENABLED="1"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"

and i try to send data to server by following way:

`curl -X PUT --data '{"last_name":"new last", "first_name":"new first"}' http://127.0.0.1:3000/person?id=3`

and then the server get it by 

       `first_name := c.PostForm("first_name")
         last_name := c.PostForm("last_name")`
but i got `nil` instead . How can i do ?

**Comment by thinkerou** [comment] 2018-06-20 11:19
gin version?

**Comment by land-pack** [comment] 2018-06-20 14:24
@thinkerou Think you for you remind, it's work for me.

`curl -X PUT -d last_name='aa' -d first_name='ss' http://127.0.0.1:3000/person?id=3`

By the way, my gin is latest for current

**Comment by thinkerou** [comment] 2018-06-21 01:34
@land-pack you are welcome, if the issue is ok please close it, thanks.

**Closed** 2018-06-21 01:46 UTC
