### ISSUE TITLE
Context Bind methods are aborting with status code, which is preventing header updates in after request middleware

### ISSUE THREAD

**Issue by AlexeyAtIgloo** [gin-gonic/gin#840] opened 2017-03-17 18:46 UTC
I have post request middleware that looks at presence of errors on the context. And is there are errors, I'm creating specific JSON response that complies with our defined contract.

It mostly works for everything as I use c.Abort() method across my application.

I'm trying to use BingJSON method to parse request body, and when it fails it will write 400 error code onto response and prevents me from changing response header later.

Here is where it is happening:
[https://github.com/gin-gonic/gin/blob/32cab500ecc71d2975f5699c8a65c6debb29cfbe/context.go#L333](https://github.com/gin-gonic/gin/blob/32cab500ecc71d2975f5699c8a65c6debb29cfbe/context.go#L333)

For now I have implemented helper function that does safe bind for me:
```go
func SafeJSONBind(obj interface{},c *gin.Context) error {
	if err := binding.JSON.Bind(c.Request, obj); err != nil {
		return err
	}
	return nil
}
``` 

But it would be nice to have option to perform bind that does c.Abort() instead of c.AbortWithError()

**Comment by tapir** [comment] 2017-03-29 21:48
+1 for this. I want to handle unvalidated structs myself.

I don't know if there is similar behaviour throughout the library but wouldn't it make more sense to not write anything to the response without explicitly being told by the developer?

**Comment by AlexeyAtIgloo** [comment] 2017-03-30 00:44
looks like this is fixed by #636 but was not merged yet...

**Comment by appleboy** [comment] 2017-03-30 04:11
Yes. I confirmed #636 PR can fix this problem.

the following is my example code.

```go
package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Login Binding from JSON
type Login struct {
	User     string `form:"user" json:"user" binding:"required"`
	Password string `form:"password" json:"password" binding:"required"`
}

func main() {
	router := gin.Default()

	// Example for binding JSON ({"user": "manu", "password": "123"})
	router.POST("/loginJSON", func(c *gin.Context) {
		var json Login
		err := c.BindJSON(&json)
		if err == nil {
			if json.User == "manu" && json.Password == "123" {
				c.JSON(http.StatusOK, gin.H{"status": "you are logged in"})
			} else {
				c.JSON(http.StatusUnauthorized, gin.H{"status": "unauthorized"})
			}
		} else {
			c.AbortWithStatusJSON(http.StatusBadGateway, gin.H{
				"error": err.Error(),
			})
		}
	})

	// Listen and serve on 0.0.0.0:8080
	router.Run(":8080")
}
```
![screen shot 2017-03-30 at 12 10 09 pm](https://cloud.githubusercontent.com/assets/21979/24487415/e1b93734-1541-11e7-952c-36c9f60ae007.png)

we need to review #636 and fix testing.

cc @javierprovecho

**Comment by tapir** [comment] 2017-03-30 04:50
This pretty much break all the codes that rely on abort when there is a
bind error. does that mean it will not be merged since gin claims not
breaking API?

**Comment by AlexeyAtIgloo** [comment] 2017-03-30 12:22
@tapir Good point, not sure that are the standards on this project, if so, new non aborting bind methods would be nice

**Closed** 2017-10-23 09:14 UTC
