### ISSUE TITLE
Request.Body.Read get body data lost

### ISSUE THREAD

**Issue by yueyongyue** [gin-gonic/gin#2374] opened 2020-05-13 03:52 UTC
## Description

Request.Body.Read get body data lost

## How to reproduce

```
package main

g := gin.Default()
	g.POST("/kubernetes/api/v1.10/controller", func(c *gin.Context) {
		jsons := make([]byte, c.Request.ContentLength)
		fmt.Println(c.Request.ContentLength)
		if _, err := c.Request.Body.Read(jsons); err != nil {
			if err.Error() != "EOF" {
				return
			}
		}
		fmt.Println(jsons)
		fmt.Println(string(jsons))
		c.String(200, "Hello %s", c.Param("name"))
	})
	g.Run(":8080")
```

## Expectations

```
$ curl --location --request POST 'http://192.168.138.128:8080/kubernetes/api/v1.10/controller?productId=100&namespace=default&cluster=c_6812529878I&type=json' \
--header 'Content-Type: application/json' \
--header 'Content-Type: text/plain' \
--data-raw '{
    "kind": "Deployment",
    "apiVersion": "apps/v1",
    "metadata": {
        "name": "ffff",
        "namespace": "default",
        "selfLink": "/apis/apps/v1/namespaces/default/deployments/ffff",
        "uid": "fd9a29af-344a-4bdd-bd76-bf3876c7d4b8",
        "resourceVersion": "51091212",
        "generation": 14,
        "creationTimestamp": "2020-05-07T08:21:23Z",
        "labels": {
            "app": "ffff"
        },
        "annotations": {
            "deployment.kubernetes.io/revision": "14"
        }
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "matchLabels": {
                "app": "ffff"
            }
        },
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "app": "ffff"
                }
            },
            "spec": {
                "containers": [
                    {
                        "name": "ffff-35kd89",
                        "image": "nginx",
                        "ports": [
                            {
                                "name": "aaaaa",
                                "containerPort": 80,
                                "protocol": "TCP"
                            }
                        ],
                        "resources": {},
                        "livenessProbe": {
                            "tcpSocket": {
                                "port": "df"
                            },
                            "initialDelaySeconds": 1,
                            "timeoutSeconds": 1,
                            "periodSeconds": 10,
                            "successThreshold": 1,
                            "failureThreshold": 3
                        },
                        "readinessProbe": {
                            "tcpSocket": {
                                "port": 90
                            },
                            "initialDelaySeconds": 1,
                            "timeoutSeconds": 1,
                            "periodSeconds": 10,
                            "successThreshold": 1,
                            "failureThreshold": 3
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File",
                        "imagePullPolicy": "IfNotPresent"
                    }
                ],
                "restartPolicy": "Always",
                "terminationGracePeriodSeconds": 30,
                "dnsPolicy": "ClusterFirst",
                "securityContext": {},
                "schedulerName": "default-scheduler"
            }
        },
        "strategy": {
            "type": "RollingUpdate",
            "rollingUpdate": {
                "maxUnavailable": "25%",
                "maxSurge": "25%"
            }
        },
        "revisionHistoryLimit": 10,
        "progressDeadlineSeconds": 600
    },
    "status": {
        "observedGeneration": 14,
        "replicas": 2,
        "updatedReplicas": 1,
        "readyReplicas": 1,
        "availableReplicas": 1,
        "unavailableReplicas": 1,
        "conditions": [
            {
                "type": "Available",
                "status": "True",
                "lastUpdateTime": "2020-05-12T11:00:23Z",
                "lastTransitionTime": "2020-05-12T11:00:23Z",
                "reason": "MinimumReplicasAvailable",
                "message": "Deployment has minimum availability."
            },
            {
                "type": "Progressing",
                "status": "False",
                "lastUpdateTime": "2020-05-12T11:10:24Z",
                "lastTransitionTime": "2020-05-12T11:10:24Z",
                "reason": "ProgressDeadlineExceeded",
                "message": "ReplicaSet \"ffff-6bcd6b9f7b\" has timed out progressing."
            }
        ]
    }
}'
```

## Browser request Actual result
{
    "kind": "Deployment",
    "apiVersion": "apps/v1",
    "metadata": {
        "name": "ffff",
        "namespace": "default",
        "selfLink": "/apis/apps/v1/namespaces/default/deployments/ffff",
        "uid": "fd9a29af-344a-4bdd-bd76-bf3876c7d4b8",
        "resourceVersion": "51091212",
        "generation": 14,
        "creationTimestamp": "2020-05-07T08:21:23Z",
        "labels": {
            "app": "ffff"
        },
        "annotations": {
            "deployment.kubernetes.io/revision": "14"
        }
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "matchLabels": {
                "app": "ffff"
            }
        },
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "app": "ffff"
                }
            },
            "spec": {
                "containers": [
                    {
                        "name": "ffff-35kd89",
                        "image": "nginx",
                        "ports": [
                            {
                                "name": "aaaaa",
                                "containerPort": 80,
                                "protocol": "TCP"
                            }
                        ],
                        "resources": {},
                        "livenessProbe": {
                            "tcpSocket": {
                                "port": "df"
                            },
                            "initialDelaySeconds": 1,
                            "timeoutSeconds": 1,
                            "periodSeconds": 10,
                            "successThreshold": 1,
                            "failureThreshold": 3
                        },
                        "readinessProbe": {
                            "tcpSocket": {
                                "port": 90
                            },
                            "initialDelaySeconds": 1,
                            "timeoutSeconds": 1,
                            "periodSeconds": 10,
                            "successThreshold": 1,
                            "failureThreshold": 3
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File",
                        "imagePullPolicy": "IfNotPresent"
                    }
                ],
                "restartPolicy": "Always",
                "terminationGracePeriodSeconds": 30,
                "dnsPolicy": "ClusterFirst",
                "securityContext": {},
                "schedulerName": "default-scheduler"
            }
        },
        "strategy": {
            "type": "RollingUpdate",
            "rollingUpdate": {
                "maxUnavailable": "25%",
                "maxSurge": "25%"
            }
        },
        "revisionHistoryLimit": 10,
        "progressDeadlineSeconds": 600
    },
    "status": {
        "observedGeneration": 14,
        "replicas": 2,
        "updatedReplicas": 1,
        "readyReplicas": 1,
        "availableReplicas": 1,
        "unavailableReplicas": 1,
        "conditions": [
            {
                "type": "Available",
                "status": "True",
                "lastUpdateTime": "2020-05-12T11:00:23Z",
                "lastTrans

## Explanation
`json data is no longer complete`
c.Request.ContentLength = 4039
The actual reception is less than 4039
`Browser request cannot get full json, curl can`

## Environment

- go version: 1.14
- gin version (or commit ref): v1.6.2
- operating system: Ubuntu 18.04.1 LTS

**Comment by buildscientist** [comment] 2020-05-13 07:35
@yueyongyue 
How are you doing a POST with a browser? Are you submitting a form or using a tool like Postman?

When I run your example code the JSON payload is 3926 bytes not 4039.

**Comment by yueyongyue** [comment] 2020-05-13 07:44
@buildscientist  Postman generates HTTP Code. Postman Version v7.23.0
```
POST /kubernetes/api/v1.10/controller?productId=100&namespace=default&cluster=c_6812529878I&type=json HTTP/1.1
Host: http://192.168.138.128:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVfNDY5MzU2MjMwNTVGIiwibmFtZSI6ImFvcyIsImVtYWlsIjoiYW9zQHN0YWZmLnNpbmEuY29tLmNuIiwicHJvZHVjdF9pZCI6IiIsImV4cCI6MTg1ODczNTI1N30.AJHwkbTSycB4UNjCD2vmD_bfnFm-5C56oC-KCBNkgpc
Content-Type: application/json

{
    "kind": "Deployment",
    "apiVersion": "apps/v1",
    "metadata": {
        "name": "ffff",
        "namespace": "default",
        "selfLink": "/apis/apps/v1/namespaces/default/deployments/ffff",
        "uid": "fd9a29af-344a-4bdd-bd76-bf3876c7d4b8",
        "resourceVersion": "51091212",
        "generation": 14,
        "creationTimestamp": "2020-05-07T08:21:23Z",
        "labels": {
            "app": "ffff"
        },
        "annotations": {
            "deployment.kubernetes.io/revision": "14"
        }
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "matchLabels": {
                "app": "ffff"
            }
        },
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "app": "ffff"
                }
            },
            "spec": {
                "containers": [
                    {
                        "name": "ffff-35kd89",
                        "image": "nginx",
                        "ports": [
                            {
                                "name": "aaaaa",
                                "containerPort": 80,
                                "protocol": "TCP"
                            }
                        ],
                        "resources": {},
                        "livenessProbe": {
                            "tcpSocket": {
                                "port": "df"
                            },
                            "initialDelaySeconds": 1,
                            "timeoutSeconds": 1,
                            "periodSeconds": 10,
                            "successThreshold": 1,
                            "failureThreshold": 3
                        },
                        "readinessProbe": {
                            "tcpSocket": {
                                "port": 90
                            },
                            "initialDelaySeconds": 1,
                            "timeoutSeconds": 1,
                            "periodSeconds": 10,
                            "successThreshold": 1,
                            "failureThreshold": 3
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File",
                        "imagePullPolicy": "IfNotPresent"
                    }
                ],
                "restartPolicy": "Always",
                "terminationGracePeriodSeconds": 30,
                "dnsPolicy": "ClusterFirst",
                "securityContext": {},
                "schedulerName": "default-scheduler"
            }
        },
        "strategy": {
            "type": "RollingUpdate",
            "rollingUpdate": {
                "maxUnavailable": "25%",
                "maxSurge": "25%"
            }
        },
        "revisionHistoryLimit": 10,
        "progressDeadlineSeconds": 600
    },
    "status": {
        "observedGeneration": 14,
        "replicas": 2,
        "updatedReplicas": 1,
        "readyReplicas": 1,
        "availableReplicas": 1,
        "unavailableReplicas": 1,
        "conditions": [
            {
                "type": "Available",
                "status": "True",
                "lastUpdateTime": "2020-05-12T11:00:23Z",
                "lastTransitionTime": "2020-05-12T11:00:23Z",
                "reason": "MinimumReplicasAvailable",
                "message": "Deployment has minimum availability."
            },
            {
                "type": "Progressing",
                "status": "False",
                "lastUpdateTime": "2020-05-12T11:10:24Z",
                "lastTransitionTime": "2020-05-12T11:10:24Z",
                "reason": "ProgressDeadlineExceeded",
                "message": "ReplicaSet \"ffff-6bcd6b9f7b\" has timed out progressing."
            }
        ]
    }
}
```
resault
```json
{
    "kind": "Deployment",
    "apiVersion": "apps/v1",
    "metadata": {
        "name": "ffff",
        "namespace": "default",
        "selfLink": "/apis/apps/v1/namespaces/default/deployments/ffff",
        "uid": "fd9a29af-344a-4bdd-bd76-bf3876c7d4b8",
        "resourceVersion": "51091212",
        "generation": 14,
        "creationTimestamp": "2020-05-07T08:21:23Z",
        "labels": {
            "app": "ffff"
        },
        "annotations": {
            "deployment.kubernetes.io/revision": "14"
        }
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "matchLabels": {
                "app": "ffff"
            }
        },
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "app": "ffff"
                }
            },
            "spec": {
                "containers": [
                    {
                        "name": "ffff-35kd89",
                        "image": "nginx",
                        "ports": [
                            {
                                "name": "aaaaa",
                                "containerPort": 80,
                                "protocol": "TCP"
                            }
                        ],
                        "resources": {},
                        "livenessProbe": {
                            "tcpSocket": {
                                "port": "df"
                            },
                            "initialDelaySeconds": 1,
                            "timeoutSeconds": 1,
                            "periodSeconds": 10,
                            "successThreshold": 1,
                            "failureThreshold": 3
                        },
                        "readinessProbe": {
                            "tcpSocket": {
                                "port": 90
                            },
                            "initialDelaySeconds": 1,
                            "timeoutSeconds": 1,
                            "periodSeconds": 10,
                            "successThreshold": 1,
                            "failureThreshold": 3
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File",
                        "imagePullPolicy": "IfNotPresent"
                    }
                ],
                "restartPolicy": "Always",
                "terminationGracePeriodSeconds": 30,
                "dnsPolicy": "ClusterFirst",
                "securityContext": {},
                "schedulerName": "default-scheduler"
            }
        },
        "strategy": {
            "type": "RollingUpdate",
            "rollingUpdate": {
                "maxUnavailable": "25%",
                "maxSurge": "25%"
            }
        },
        "revisionHistoryLimit": 10,
        "progressDeadlineSeconds": 600
    },
    "status": {
        "observedGeneration": 14,
        "replicas": 2,
        "updatedReplicas": 1,
        "readyReplicas": 1,
        "availableReplicas": 1,
        "unavailableReplicas": 1,
        "conditions": [
            {
                "type": "Available",
                "status": "True",
                "lastUpdateTime": "2020-05-12T11:00:23Z",
                "lastTrans

```

**Comment by yueyongyue** [comment] 2020-05-21 01:41
How to solve ？

**Comment by buildscientist** [comment] 2020-05-22 00:35
@yueyongyue Haven't had a chance to load Postman yet. Have you considered that Postman isn't properly handling the Content-Length header? 

I tested this earlier using curl and httpie and neither had truncated payloads.

**Comment by yueyongyue** [comment] 2020-05-25 01:32
I know curl is ok.  But same thing for Postman, same parameter, "net/http" is ok
```
package main

import (
	"fmt"
	//"github.com/gin-gonic/gin"
	"io/ioutil"
	"net/http"
)

func IndexHandler(w http.ResponseWriter, r *http.Request) {
	s, _ := ioutil.ReadAll(r.Body)
	fmt.Println(string(s))
}
func main() {
	http.HandleFunc("/kubernetes/api/v1.10/controller", IndexHandler)
	http.ListenAndServe("0.0.0.0:8080", nil)
}
```

**Comment by buildscientist** [comment] 2020-05-25 17:41
@yueyongyue 

The issue isn't with Gin but a combo of your code and how Postman handles HTTP requests.

In your compound conditional `if _, err := c.Request.Body.Read(jsons); err != nil` you are only reading a portion of the full request body. 

Instead of ignoring the first parameter returned by Read() if you assign it to a variable you'll notice that its value is 3809 bytes instead of the 3926 being set in the Content-Length header.

`if bytesRead, err := c.Request.Body.Read(jsons); err != nil //bytesRead ==  3809`

Check out the docs on the [io.Read()](https://golang.org/pkg/io/#Reader) of the Reader interface.

You need to continue reading the request body into your byte array until the peer (in this case Postman) completes sending over the payload. It's unclear to me why Postman is behaving this way even with accept/transfer-encoding headers missing.

I hacked something together as follows which works: 

```
	defer c.Request.Body.Close()
	bytesRead := -1
	var err error
	for bytesRead != 0 {
			requestChunk := make([]byte, c.Request.ContentLength)
			bytesRead, err = c.Request.Body.Read(requestChunk)
			log.Println(err)
			log.Println(bytesRead)
			jsons = append(jsons, requestChunk...)
		}
```

Note: My implementation has the added effect of having to create a new slice every time you try to read from the peer. Since you're handling JSON have you considered using Gin's request binder? 

I don't know what your use case is but if you use something like `context.ShouldBindJSON` it will handle deserializing to the specified struct.

**Comment by yueyongyue** [comment] 2020-05-29 07:20
I don't know why,   `json, err := ioutil.ReadAll(c.Request.Body) ` is ok,  I'll use it

**Comment by linxing** [comment] 2020-06-18 08:55
same issue

**Comment by buildscientist** [comment] 2020-06-27 01:42
@yueyongyue I encourage you to read the Go docs and understand the difference between [ioutil.ReadAll](https://golang.org/pkg/io/ioutil/#ReadAll) and [io.Read](https://golang.org/pkg/io/#Reader)

Simply put ioutil.ReadAll reads the *entire* buffer until the EOF (end of file) mark reached. As stated in my previous message the issue you're having is not with the Gin Gonic framework but with your implementation. 

@appleboy Would recommend closing this issue out.

**Comment by appleboy** [comment] 2020-06-27 02:27
@buildscientist Great. Thanks.

**Closed by appleboy** 2020-06-27 02:27 UTC
