### ISSUE TITLE
when release next version?

### ISSUE THREAD

**Issue by wongoo** [gin-gonic/gin#1420] opened 2018-07-02 10:08 UTC
it's a long time from the latest v1.2 released on Jul 2, 2017, when will be the next version released?

**Comment by tyan-boot** [comment] 2018-07-12 13:44
New release needed.

My project which depends on "ShouldBindJSON" broken when i use v1.2 instead master. I use dep to update my dependences.

**Comment by junweiyang** [comment] 2018-07-13 03:01
@javierprovecho please

**Comment by appleboy** [comment] 2018-07-16 02:43
duplicate of #1239

**Closed by appleboy** 2018-07-16 02:43 UTC
