### ISSUE TITLE
request middleware get relativePath 

### ISSUE THREAD

**Issue by johnhjwsosd** [gin-gonic/gin#1759] opened 2019-02-01 13:16 UTC
- go version:1.11
- gin version (or commit ref): master

## Description

Hello,

I want to get the relativePath of the request in the request middleware to make some judgments. What should I do?
```

router.User(middlerWare)
router.POST("/hi/:name", func(c *gin.Context) {
       	c.JSON(200,"")
})

func middlerWare(c *gin.Context){
	fmt.Println(c.Request.URL.Path)
}
```

curl -get 127.0.0.1/hi/gin
I want it print `/hi/:name` not `/hi/gin`

**Comment by thoeni** [comment] 2019-02-01 16:54
Not sure that can be done out of the box as at that point parameters have been already replaced.
You could replace them back again (do you _really_ need it?) replacing the values with the keys in the params slice...
```go
path := c.Request.URL.Path
for _, param := range c.Params {
	path = strings.Replace(path, param.Value, ":"+param.Key, -1)
}
fmt.Println(path)
```

**Comment by mi4tin** [comment] 2019-02-02 03:14
> Not sure that can be done out of the box as at that point parameters have been already replaced.
> You could replace them back again (do you _really_ need it?) replacing the values with the keys in the params slice...
> 
> ```go
> path := c.Request.URL.Path
> for _, param := range c.Params {
> 	path = strings.Replace(path, param.Value, ":"+param.Key, -1)
> }
> fmt.Println(path)
> ```
> 
> Also I think this is not an "issue", more of a question à la "stackoverflow"... I'd probably close this.

It's not safe in this way.

**Comment by johnhjwsosd** [comment] 2019-02-12 08:06
> Not sure that can be done out of the box as at that point parameters have been already replaced.
> You could replace them back again (do you _really_ need it?) replacing the values with the keys in the params slice...
> 
> ```go
> path := c.Request.URL.Path
> for _, param := range c.Params {
> 	path = strings.Replace(path, param.Value, ":"+param.Key, -1)
> }
> fmt.Println(path)
> ```
> 
> Also I think this is not an "issue", more of a question à la "stackoverflow"... I'd probably close this.




If the routing is a/:arga/b/:argb requesting a/1/b/1, an error will occur.

Can you provide a parameter or expose a method in context?

**Comment by thoeni** [comment] 2019-02-13 23:53
> If the routing is a/:arga/b/:argb requesting a/1/b/1, an error will occur.

Right, I had one `-` too many:
```go
path := c.Request.URL.Path
for _, param := range c.Params {
	path = strings.Replace(path, param.Value, ":"+param.Key, 1)
}
fmt.Println(path)
```

Since `c.Params` is a slice, if you use the `strings.Replace(path, param.Value, ":"+param.Key, 1)`
```go
// Replace returns a copy of the string s with the first n
// non-overlapping instances of old replaced by new.
```

This means that even `a/1/b/1` should work as params will look like:
```go
c.Params := []Param{{"arga", "1"}, {"argb", "1"}}
```
and while replacing it would pick the first param `{"arga", "1"}` and replace the first `1` with `:arga`, then move on to the next param `{"argb", "1"}` and replace the second `1` with `:argb`...

A better way to rebuild the endpoint would be accessing the engine, which is unexported, so can't do that: https://github.com/gin-gonic/gin/blob/master/context.go#L51

**Comment by johnhjwsosd** [comment] 2019-02-15 07:42
> > If the routing is a/:arga/b/:argb requesting a/1/b/1, an error will occur.
> 
> Right, I had one `-` too many:
> 
> ```go
> path := c.Request.URL.Path
> for _, param := range c.Params {
> 	path = strings.Replace(path, param.Value, ":"+param.Key, 1)
> }
> fmt.Println(path)
> ```
> 
> Since `c.Params` is a slice, if you use the `strings.Replace(path, param.Value, ":"+param.Key, 1)`
> 
> ```go
> // Replace returns a copy of the string s with the first n
> // non-overlapping instances of old replaced by new.
> ```
> 
> This means that even `a/1/b/1` should work as params will look like:
> 
> ```go
> c.Params := []Param{{"arga", "1"}, {"argb", "1"}}
> ```
> 
> and while replacing it would pick the first param `{"arga", "1"}` and replace the first `1` with `:arga`, then move on to the next param `{"argb", "1"}` and replace the second `1` with `:argb`...
> 
> A better way to rebuild the endpoint would be accessing the engine, which is unexported, so can't do that: https://github.com/gin-gonic/gin/blob/master/context.go#L51

Right, the above solutions for strings.Replace may still have errors, like
Routing a/:arga/b/:argb
Request a/a/b/b
The result would be :arga/a/:argb/b
Ability to access Engine or add a parameter like Params in context

**Comment by mi4tin** [comment] 2019-02-15 09:48
....

**Comment by thoeni** [comment] 2019-02-15 17:42
> Right, the above solutions for strings.Replace may still have errors, like
> Routing a/:arga/b/:argb
> Request a/a/b/b

Yes, I was suggesting a sort of "workaround", not a feature for the product (I don't think that would be much needed)... if you end up with a `a/a/b/b` I think the API could be designed differently anyway.

**Comment by Dominik-K** [comment] 2019-10-18 11:20
PR #1826 adds `gin.Context.FullPath()`.

This issue is (somehow) a duplicate of #748.

**Closed** 2019-10-18 12:02 UTC
