### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by DeadNumbers** [gin-gonic/gin#866] opened 2017-04-05 07:03 UTC
```
go get -u gopkg.in/gin-gonic/gin.v1
# gopkg.in/gin-gonic/gin.v1
../../go/src/gopkg.in/gin-gonic/gin.v1/context.go:498: cannot use sse.Event literal (type sse.Event) as type render.Render in argument to c.Render:
	sse.Event does not implement render.Render (missing WriteContentType method)

```

**Comment by appleboy** [comment] 2017-04-05 07:19
duplicate of https://github.com/gin-gonic/gin/issues/828

**Closed by appleboy** 2017-04-05 07:19 UTC
