### ISSUE TITLE
Correct way to validate forms (json binding)

### ISSUE THREAD

**Issue by dimuska139** [gin-gonic/gin#1907] opened 2019-05-20 15:15 UTC
- go version: go1.12.4 linux/amd64
- gin version (or commit ref): v1.4.0
- operating system: Linux Ubuntu 4.15.0-50-generic

## Description
Gin validates form data after calling mapForm. So if form (golang struct) has field with type int and user sends data in string format (for example it sends number in quotes), Bind method (I mean json binding) returns *strconv.NumError which can not be associated with specific field. How to resolve this situations?
`{
"age": 1
}`

`{
"age": "1"
}`

**Comment by torkelrogstad** [comment] 2019-10-10 15:51
The underlying problem here is a duplicate of #1093

**Closed** 2019-10-10 16:58 UTC
