### ISSUE TITLE
Middlewares will always be executed even if there is response/return in previous middleware

### ISSUE THREAD

**Issue by dxfeng10** [gin-gonic/gin#290] opened 2015-05-16 05:30 UTC
Middlewares will always be executed even if there is a response in one of the middlewares.  

// Gin context code: 
```go
func (c *Context) Next() {
	c.index++
	s := int8(len(c.handlers))
	for ; c.index < s; c.index++ {
		c.handlers[c.index](c)
	}
}
```
// compare with Martini:
```go
func (r *routeContext) Next() {
	r.index += 1
	r.run()
}
func (r *routeContext) run() {
	for r.index < len(r.handlers) {
		handler := r.handlers[r.index]
		vals, err := r.Invoke(handler)
		if err != nil {
			panic(err)
		}
		r.index += 1

		// if the handler returned something, write it to the http response
		if len(vals) > 0 {
			ev := r.Get(reflect.TypeOf(ReturnHandler(nil)))
			handleReturn := ev.Interface().(ReturnHandler)
			handleReturn(r, vals)
		}

		if r.Written() {
			return
		}
	}
}
```

**Comment by manucorporat** [comment] 2015-05-16 12:21
Are you sure this is not an expected behaviour? it sound like an important side effect for writing. Nobody likes side effects.

> Side effects are lies. Your function promises to do one thing, but it also does other hidden things. Sometimes it will make unexpected changes to the variables of its own class. Sometimes it will make them to the parameters passed into the function or to system glo- bals. In either case they are devious and damaging mistruths that often result in strange temporal couplings and order dependencies.

Robert C. Martin (Clean Code)


thoughts?

**Comment by nazwa** [comment] 2015-05-16 12:55
I agree with @manucorporat here, middleware should only break the flow if explicitly asked to. This is quite similar to my question from last week #287.

**Comment by manucorporat** [comment] 2015-05-16 15:34
I am thinking about I do not want to close this issue.
and @dxfeng10 may be right... let me explain:

c.JSON
c.XML
c.String

are high level methods for building the response, they should be just called once...

**Comment by dxfeng10** [comment] 2015-05-18 14:37
@manucorporat  yes, not only c.JSON, c.XML, c.String , also the static middleware,  the middlewares after static such as cors,gzip,auth... should not be executed. I think Martini handles this very well. please take a look.

**Comment by manucorporat** [comment] 2015-05-18 14:55
cors,gzip,auth middleware are always before the handler. can you give me an use case where it is convenient to abort after rendering?

**Comment by dxfeng10** [comment] 2015-05-19 17:52
I think
1. middlewares after static should not be executed, cuz file as a response.
2. middlewares or handler after auth should not be executed if auth failed(a json message will be returned/responsed if failed in my custom auth middleware)

```go
r := gin.Default()
	r.Use(secure.Secure(secure.Options{
		SSLRedirect:   true,
		SSLHost:       "localhost:9443",
		IsDevelopment: false,
	}))
    r.Use(gzip.Gzip(gzip.DefaultCompression))	
	r.Use(static.Serve("/public", static.LocalFile("public", false)))	
	r.Use(cors.Middleware(cors.Config{
		Origins:         "*",
		Methods:         "PUT, POST",
		RequestHeaders:  "Origin, Authorization, x-requested-with, Content-Type, Content-Range, Content-Disposition, Content-Description",
		ExposedHeaders:  "Content-Length",
		MaxAge:          24 * time.Hour,
		Credentials:     false, 
		ValidateHeaders: false,
	}))		
	r.Use(auth.Auth())
    // other middlewares...
```

**Comment by manucorporat** [comment] 2015-05-19 18:03
I have been thinking about this and asked very good pragmatic and theorical engineers.
The final decision, is 
- No side effects
- No magic
- Explicit > Implicit
- Go Idiomatic: be explicit

c.Render(), c.JSON, c.XML and so on... are not going to abort() the handlers chain. Instead a call to `Abort()` is needed.

take the following examples:
```go
if authFailed {
    c.JSON(200, gin.H{"message": "signature doesn't match"})
    c.Abort()
}
```

```go
if authFailed {
    c.JSON(200, gin.H{"message": "signature doesn't match"})
}
```

which one looks more understandable? I want developers be EXPLICIT. so you can ask questions easily. c.JSON just do that. it renders some JSON, no side effects. Simple documentation, I meant, no documentation at all.

1st example:
Why is the handlers chain aborted? because you are callling abort.

2nd exmaple:
Why is the handlers chain aborted? because... well, you are rendering some json, and Gin under the hoods is aborting the chain.

**Comment by manucorporat** [comment] 2015-05-19 18:22
@dxfeng10 https://github.com/gin-gonic/gin/blob/bb98ec0490306d037e8ca906899d27bc68902c47/auth.go#L56-L59

If you have trouble with Gin, like something is not working or you are not sure, please ask. I am sure I can help.

**Closed by manucorporat** 2015-05-19 18:22 UTC
