### ISSUE TITLE
[GIN-debug] redirecting request 307

### ISSUE THREAD

**Issue by almgwary** [gin-gonic/gin#1004] opened 2017-07-11 03:18 UTC
i didn't found any answer for this issue .
I am trying to call simple API, but it `redirecting request 307` . and the request fail on client side .
as you see in the first screen shot there is 3 requests . first one is option with `Status Code:200 OK` .
the next 2 requests with `Status Code:307 Temporary Redirect`
port 3030 is server
port 8100 is client 
CORS middleware is [gin-cors](https://github.com/itsjamie/gin-cors)

![image](https://user-images.githubusercontent.com/7817756/28049448-c65bc4be-65f7-11e7-8711-c2f6f7ac00a0.png)

![image](https://user-images.githubusercontent.com/7817756/28049470-ec6c8db4-65f7-11e7-9d94-40801228bed6.png)

![image](https://user-images.githubusercontent.com/7817756/28049481-f928298c-65f7-11e7-9029-95a1d59b79fa.png)

and this is the code 
```go
// Creates a gin router with default middleware:
	router := gin.Default()
	// Apply the middleware to the router (works with groups too)
	router.Use(cors.Middleware(cors.Config{
		Origins:        "*",
		Methods:        "GET, PUT, POST, DELETE",
		RequestHeaders: "Origin, Authorization, Content-Type",
		ExposedHeaders: "",
		MaxAge: 300 * time.Second,
		Credentials: false,
		ValidateHeaders: false,
	}))

       router.POST("/api/v1/login", usersController.Login)
```
client side error 
```
XMLHttpRequest cannot load http://localhost:3030/api/v1/login/. Redirect from
 'http://localhost:3030/api/v1/login/' to 'http://localhost:3030/api/v1/login' has been blocked by CORS 
policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 
'http://localhost:8100' is therefore not allowed access.

```

it works fine on postman

**Comment by javierprovecho** [comment] 2017-07-11 08:28
@almgwary I see two different hosts (port 8100 and 3030), also which cors middleware are you using?

**Comment by almgwary** [comment] 2017-07-11 11:07
port 3030 is server
port 8100 is client 
CORS middleware is [gin-cors](github.com/itsjamie/gin-cors)

**Comment by javierprovecho** [comment] 2017-07-11 11:48
@almgwary In the 1st screenshot it shows that the allowed host is the one with port 8100, not the one you're making the request from.

This may be a bug or a misconfiguration from the middleware, so you should open an issue there (as I saw you did, https://github.com/itsjamie/gin-cors/issues/9).

You can also try a different cors middleware like [`github.com/gin-contrib/cors`](https://github.com/gin-contrib/cors)

closing as the issue is not related with gin itself

**Closed by javierprovecho** 2017-07-11 11:48 UTC

**Comment by almgwary** [comment] 2017-07-11 15:46
SOLVED

problem was with URL 

- `...url/login ` **Passed** 
- `...url/login/ ` **Failed** because of extra `/`

**Comment by javierprovecho** [comment] 2017-07-11 16:08
@almgwary good catch, check https://github.com/gin-gonic/gin/blob/master/gin.go#L58-L63 too

**Comment by hellojukay** [comment] 2017-07-26 09:59
i think , this is a bug, if your url is /login ,it well return http 200 ,but if /login/ it will return http 307.

**Comment by estebanborai** [comment] 2019-12-11 00:33
> SOLVED
> 
> problem was with URL
> 
>     * `...url/login ` **Passed**
> 
>     * `...url/login/ ` **Failed** because of extra `/`

Same issue
